# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://ice1000.org
date_format: "ordinal"
name: "ice1000's Blog"
title: ice1000 >>= akiris
subtitle: "知其变，守其恒，为天下式"
description: "ice1000's blog"
keywords: ice1000, Akiris, blog
favicon: /favicon.ico
# timezone: Asia/ChengDu
encoding: "utf-8"
side_bar_repo_limit: 6

# ---------------- #
#      Author      #
# ---------------- #
author: Tesla Ice Zhang >>= Akiris Wu
github_username: ice1000
github_username2: AkimotoAkari
organization: Working Together
location: ChengDu, China
email: ice1000kotlin@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Archieve

  -
    href: /resume/
    label: Resume

  -
    href: /links/
    label: Links

  -
    href: /projects/
    label: Projects

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
auto: true
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ice1000/ice1000.github.io

